#!/usr/bin/env python
# -*- coding: utf-8 -*-

def try_me():
    meal = input("What are you hungry for? ")
    return f"Alright, try this {meal} I just pulled fresh out of the oven!"

if __name__ == "__main__":
    print(try_me())
